config/routes.rb
Rails.application.routes.draw do
  # Define suas rotas de aplicação usando o DSL em https://guides.rubyonrails.org/routing.html

  get '/login', to: 'application#login', as: :login
  post '/login', to: 'application#home'

  get '/login/cadastrar_nova_amostra', to: 'home#cadastrar_nova_amostra', as: :cadastrar_nova_amostra
  post '/login/cadastrar_nova_amostra', to: 'home#cadastra_nova_amostra'

  get '/login/retirar_amostra', to: 'home#retirar_amostra', as: :retirar_amostra
  post '/login/retirar_amostra', to: 'home#retirar_amostra', as: :retirar_amostra_post

  get '/busca_amostra', to: 'home#busca_amostra', as: 'busca_amostra'
  #get '/busca_amostra', to: 'home#busca_amostra', as: :busca_amostra
  #get '/busca_amostra', to: 'busca#busca_amostra'

  get '/api/amostras_biorepositorio', to: 'amostras_biorepositorio#index'

  get '/coleta', to: 'coleta#new'
  post '/coleta', to: 'coleta#create'

  get '/recebimento', to: 'recebimento#received'
  post '/recebimento', to: 'recebimento#received'

  #get '/recebimento/filtrar', to: 'recebimento#filtrar', as: :recebimento_filtrar
  post '/recebimento/filtrar', to: 'recebimento#filtrar', as: :recebimento_filtrar
  post '/recebimento/filtrar', to: 'recebimento#filtrar', as: 'filtrar_recebimento'


#get '/recebimento/filtrar', to: 'recebimento#filtrar'
  #post '/recebimento', to: 'recebimento#received'



  # Define a rota raiz ("/")
  root 'application#login'

  # Adiciona a rota para a ação create do controlador AmostrasController
  resources :amostras, only: [:create]
end

app/models/AmostraBiorepositorio.rb
class AmostraBiorepositorio < ApplicationRecord
  self.table_name = "amostras_biorepositorio"

  # Mapeamento dos atributos para as colunas no banco de dados
  attribute :resp_cadastro, :string
  attribute :id, :integer
  attribute :nome, :string
  attribute :descricao, :string

  attribute :nome_paciente, :string
  attribute :cpf, :string
  attribute :rg, :string
  attribute :nome_coletora, :string
  attribute :projeto, :string

  # Adiciona os novos atributos
  attribute :numero_amostra, :integer
  attribute :data_coleta, :date
  attribute :id_projeto, :integer

  # validates :nome_paciente, presence: true
  # validates :cpf, presence: true
  # validates :rg, presence: true
  # validates :nome_coletora, presence: true
  # validates :projeto, presence: true

  def self.create_from_form(form_params)
    amostra = AmostraBiorepositorio.new(form_params)
    amostra.save
    #amostra
  end
end

app/models/acesso_usuario.rb
class AcessoUsuario < ApplicationRecord
  validates :username, presence: true, uniqueness: true

  def authenticate(password)
    self.password == password
  end
end #continuar a partir daqui na implementação da autenticação dos usuários em banco de dados.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/amostra_biorepositorio.rb
class AmostraBiorepositorio < ApplicationRecord
  self.table_name = "amostras_biorepositorio"
end

app/controllers/AmostrasBiorepositorioController.rb
# app/controllers/amostras_biorepositorio_controller.rb

class AmostrasBiorepositorioController < ApplicationController
  def index
    data = AmostraBiorepositorio.select(:numero_amostra, :data_coleta, :resp_cadastro)
    render json: data
  end

  def retirar_amostras
    AmostraBiorepositorio.destroy_all(id: params[:ids])
    redirect_to amostras_biorepositorio_path, notice: "Amostras retiradas com sucesso."
  end
end

app/controllers/AmostrasController.rb
require "action_controller/railtie"


class AmostrasController < ApplicationController
  def create
    amostra = AmostraBiorepositorio.new(numero_amostra: params[:numero], data_coleta: params[:data], id_projeto: params[:projeto], resp_cadastro: params[:pessoa], tipo_material: params[:tipo_amostra])
    if amostra.save
      flash[:notice] = "Amostra cadastrada com sucesso!"
      redirect_to cadastrar_nova_amostra_path # Altere para a página correta de destino
    else
      flash[:notice] = "Amostra não foi registrada por algum motivo :("
      redirect_to new_amostra_path # Altere para a página correta de destino
    end
  end
end

app/controllers/ApplicationController.rb
require "action_controller/railtie"

class ApplicationController < ActionController::Base
  def login
    if request.post?  # Verifica se o formulário foi enviado via POST
      usuario = params[:usuario]
      senha = params[:senha]

      # Verifique as credenciais do usuário (substitua esta lógica com sua própria autenticação)
      if usuario == "admin" && senha == "346722"
        # Se as credenciais estiverem corretas, redirecione para a página de sucesso ou faça a lógica necessária
        redirect_to root_path, notice: "Login bem-sucedido!"
      else
        # Se as credenciais estiverem incorretas, redirecione para a página de login com uma mensagem de erro
        redirect_to login_path, alert: "Usuário ou senha inválidos!"
      end
    end
    #head :no_content
    #render "login"
  end
end

app/controllers/BuscaController.rb
# app/controllers/busca_controller.rb

class BuscaController < ApplicationController
  def index
    @resultados = []
  end

  def busca_amostra
    search_query = params[:search_query]
    @resultados = AmostraBiorepositorio.where("numero_amostra LIKE ?", "%#{search_query}%")
  end
end

app/controllers/ColetaController.rb
class ColetaController < ApplicationController
  def new
    render 'coleta'
    amostra = AmostraBiorepositorio.new
    # @amostra = AmostraBiorepositorio.new(numero_amostra: params[:cpf], data_coleta: Date.today, id_projeto: params[:projeto], resp_cadastro: params[:nome_coletora], nome_paciente: params[:nome_paciente])
    
    
  end
  def create
    @amostra = AmostraBiorepositorio.new(numero_amostra: params[:cpf], data_coleta: Date.today, id_projeto: params[:projeto], resp_cadastro: params[:nome_coletora], nome_paciente: params[:nome_paciente])
   
    if @amostra.save
      #flash[:success] 
      print "Dados Enviados com sucesso"
      redirect_to '/coleta'
    else
       flash[:success] = "Dados não gravados pois houve algum erro no Controller :("
    end
  end
 
end

app/controllers/HomeController.rb
class HomeController < ApplicationController
  def cadastrar_nova_amostra
    render 'cadastraNovaAmostra'
  end

  def retirar_amostra
    render 'retirarAmostra'
  end

  def busca_amostra
    # Lógica para buscar os resultados no banco de dados ou definir um valor padrão
    @resultados = AmostraBiorepositorio.all

    render 'busca_amostra'
  end

end

app/controllers/RecebimentoController.rb
class RecebimentoController < ApplicationController
  def received
    @amostras = AmostraBiorepositorio.all
    @registros = []
    render 'recebimento', locals: { amostras: AmostraBiorepositorio.pluck(:nome_coletora), registros: @registros }
  end

  def filtrar
    @amostras = AmostraBiorepositorio.all
    @registros = AmostraBiorepositorio.where(nome_coletora: params[:coletora])
    render 'recebimento', locals: { amostras: AmostraBiorepositorio.pluck(:nome_coletora), registros: @registros }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/busca_amostra.html.erb
<!-- app/views/busca/index.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Tela de Busca</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');

    * {
      margin: 0;
      border: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: "Poppins", sans-serif;
    }

    body {
      background: linear-gradient(45deg, #000000, #ffffff);
      background-repeat: no-repeat;
      min-height: 100vh;
      min-width: 100vw;
      display: grid;
      place-items: center;
    }

    .grid-container {
      background: white;
      min-width: 500px;
      min-height: 50vh;
      padding: 2rem;
      box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);
      border-radius: 8px;
      position: relative;
    }

    .logo {
      font-weight: 600;
      font-size: 1.5rem;
      margin-bottom: 1rem;
    }

    .search-box {
      display: flex;
      align-items: center;
      margin-bottom: 1rem;
    }

    .search-input {
      flex: 1;
      padding: 0.5rem;
      border-radius: 4px;
      border: 1px solid #ccc;
      font-size: 1rem;
    }

    .search-button {
      background-color: #333333;
      color: white;
      padding: 0.5rem 1rem;
      border: none;
      border-radius: 4px;
      font-size: 1rem;
      cursor: pointer;
    }

    .search-button:hover {
      background-color: #555555;
    }

    .tabs {
      display: flex;
      margin-bottom: 1rem;
    }

    .tab {
      padding: 0.5rem 1rem;
      background-color: #f2f2f2;
      cursor: pointer;
      border-radius: 4px;
      margin-right: 0.5rem;
    }

    .tab.active {
      background-color: #ddd;
    }

    .pages {
      display: none;
    }

    .pages.active-page {
      display: block;
    }

    table {
      width: 100%;
      text-align: center;
    }

    th, td {
      padding: 0.5rem;
    }

    th {
      font-weight: 600;
    }

    .print-button {
      position: absolute;
      top: 1rem;
      right: 1rem;
      background-color: black;
      color: white;
      padding: 0.5rem 1rem;
      border: none;
      border-radius: 2px;
      font-size: 1.2rem;
      cursor: pointer;
    }

    .print-button:hover {
      background-color: #333333;
    }

    .retirar-button:hover{
      background-color: #333333;
    }

    .retirar-button {
      position: absolute;
      top: 1rem;
      right: 8rem;
      background-color: black;
      color: white;
      padding: 0.5rem 1rem;
      border: none;
      border-radius: 2px;
      font-size: 1.2rem;
      cursor: pointer;
    }

    .checkbox-cell {
      text-align: center;
    }

    .export-pages {
      display: none;
    }
  </style>
</head>
<body>
  <div class="grid-container">
    <div class="logo">Minha Tela de Busca</div>
    <div class="search-box">
      <input type="text" id="search-input" placeholder="Digite sua busca..." class="search-input">
      <button onclick="filterResults()" class="search-button">Buscar</button>
    </div>
    <ul class="autocomplete-list"></ul>
    <div class="tabs">
      <div class="tab active">Resultados</div>
      <div class="tab">Consultadas Recentemente</div>
    </div>
    <div class="pages active-page">
      <% if @resultados.any? %>
        <table id="resultados">
          <thead>
            <tr>
              <th>PID</th>
              <th>Data do Cadastro</th>
              <th>Tipo de Material</th>
            </tr>
          </thead>
          <tbody>
            <% @resultados.each do |resultado| %>
              <tr>
                <td><%= resultado.numero_amostra %></td>
                <td><%= resultado.data_coleta %></td>
                <td><%= resultado.tipo_material %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>Nenhum resultado encontrado.</p>
      <% end %>
    </div>
  </div>

  <script>
    function filterResults() {
      const searchQuery = document.querySelector("#search-input").value.toLowerCase();
      const rows = document.querySelectorAll("#resultados tbody tr");

      rows.forEach(row => {
        const pid = row.querySelector("td:nth-child(1)").innerText.toLowerCase();
        const dataCadastro = row.querySelector("td:nth-child(2)").innerText.toLowerCase();
        const tipoMaterial = row.querySelector("td:nth-child(3)").innerText.toLowerCase();

        if (
          pid.includes(searchQuery) ||
          dataCadastro.includes(searchQuery) ||
          tipoMaterial.includes(searchQuery)
        ) {
          row.style.display = "";
        } else {
          row.style.display = "none";
        }
      });
    }
  </script>
</body>
</html>

app/views/application/cadastraNovaAmostra.html.erb
<html>
<head>
  <link rel="icon" href="https://cdn3.iconfinder.com/data/icons/font-awesome-solid/512/dna-256.png" type="image/x-icon">
  <title>Cadastrar Nova Amostra | LAB-DFA </title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}

body {
  background: linear-gradient(45deg, #000000, #ffffff);
  background-repeat: no-repeat;
  min-height: 100vh;
  min-width: 100vw;
  display: flex;
  align-items: center;
  justify-content: center;
}

.main.container {
  background: white;
  min-width: 500px;
  min-height: 50vh;
  padding: 2rem;
  box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);
  border-radius: 8px;
}

.main h2 {
  font-weight: 600;
  margin-bottom: 4rem;
  position: relative;
}

.main h2::before {
  content: '';
      position: absolute;
      height: 3px;
      width: 45px;
      bottom: 3px;
      left: 0;
      border-radius: 8px;
      background: linear-gradient(45deg, #000000, #0f0f0f);
}

form {
  display: flex;
  flex-direction: column;
}

.input-field {
  position: relative;
}

form .input-field:first-child {
  margin-bottom: 1.5rem;
}

.input-field .underline::before {
  content: '';
  position: absolute;
  height: 1px;
  width: 100%;
  bottom: -5px;
  left: 0;
  background: rgba(0, 0, 0, 0.2);
}

.input-field .underline::after {
  content: '';
  position: absolute;
  height: 1px;
  width: 100%;
  bottom: -5px;
  left: 0;
  background: linear-gradient(45deg, #000000, #0f0f0f);
  transform: scaleX(0);
  transition: all 0.3s ease-in-out;
  transform-origin: left;
}

.input-field input:focus ~ .underline::after {
  transform: scaleX(1);
}

.input-field input {
  outline: none;
  font-size: 0.9rem;
  color: rgba(0, 0, 0, 0.7);
  width: 100%;
}

.input-field input::placeholder {
  color: rgba(0, 0, 0, 0.5);
}

form input[type="submit"] {
  margin-top: 2rem;
  padding: 0.4rem;
  width: 100%;
  background: linear-gradient(to left, #000000, #0f0f0f);
  cursor: pointer;
  color: white;
  font-size: 0.9rem;
  font-weight: 300;
  border-radius: 4px;
  transition: all 0.3s ease;
}

form input[type="submit"]:hover {
  letter-spacing: 0.5px;
  background: linear-gradient(to right, #000000, #0f0f0f);
}

.footer {
  display: flex;
  flex-direction: column;
  margin-top: 1rem;
}

.footer span {
  color: rgba(0, 0, 0, 0.7);
  font-size: 0.8rem;
  text-align: center;
}

.footer .social-field {
  padding: 0.4rem;
  border-radius: 4px;
  font-size: 0.85rem;
  width: 100%;
  cursor: pointer;
  margin-top: 1rem;
}

.footer .social-field a i {
  margin: 0 0.5rem;
  width: 15px;
}

.footer .social-field a {
  text-decoration: none;
  color: rgb(0, 0, 0);
}

.footer .social-field.twitter {
  background: white;
  border: 1px solid black;
}

.footer .social-field.facebook {
  background: white;
  border: 1px solid black;
}

.container {
  width: 80%;
  max-width: 800px;
  margin: 0 auto;
}

.logo {
  font-size: 36px;
  font-weight: bold;
  color: #2196f3;
  margin-top: 40px;
  margin-bottom: 20px;
}

.menu {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 40px;
}

.menu a {
  text-decoration: none;
  color: #2196f3;
  font-size: 14px;
}

.menu a:hover {
  text-decoration: underline;
}

.form {
  background-color: #ffffff;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 20px;
}

.form-title {
  text-align: center;
  font-size: 24px;
  margin-bottom: 20px;
}

.form input {
  display: block;
  width: 100%;
  height: 40px;
  border: none;
  outline: none;
  padding: 10px;
  font-size: 16px;
}

.form input[type="text"],
.form input[type="date"],
.form select {
  border-bottom: 1px solid #cccccc;
  margin-bottom: 20px;
}

.form input[type="submit"] {
  background-color: #2196f3;
  color: #ffffff;
  border-radius: 20px;
  cursor: pointer;
  margin-top: 20px;
}

.form input[type="submit"]:hover {
  background-color: #1976d2;


}

.notice {
  background-color: green;
  color: green;
  padding: 10px;
  border-radius: 5px;
}

.ok-sign {
  display: inline;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100vh;
}

.ok-sign img {
  width: 50px; /* Ajuste o tamanho conforme necessário */
  height: auto;
}

    </style>
</head>
<body>
      <script>
        window.setTimeout(function() {
          document.querySelector('.notice').style.display = 'none';
        }, 4000);
      </script>
    <div class="container">
        <div class="menu">
                <a href="#"><img src="https://img.icons8.com/material-rounded/24/000000/settings.png"/></a>
        </div>
        <div class="notice">
           <%= flash[:notice] %>
        </div>


    <div class="form">
      <div class="form-title">Cadastrar nova amostra</div>
      <form action="<%= amostras_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="numero" placeholder="Número da amostra" required>
  <input type="date" name="data" placeholder="Data da coleta" required>
  <select name="projeto" id="projeto" required>
    <option value="">Selecione o projeto</option>
    <option value="zikaalliance">ZikaAlliance</option>
    <option value="gab">GAB</option>
    <option value="coorte-dengue">Coorte Dengue</option>
  </select>
  <select name="tipo_amostra" id="tipo_amostra" required>
    <option value="">Selecione o tipo de amostra</option>
    <option value="Soro">Soro</option>
    <option value="Sangue Total">Sangue Total</option>
    <option value="Plasma">Plasma</option>
    <option value="Urina">Urina</option>
  </select>
  <input type="text" name="pessoa" placeholder="Pessoa que cadastrou a amostra" required>
  <input type="submit" value="CADASTRAR NOVA AMOSTRA">
</form>

<div class="notice">
  <% if flash[:notice].present? %>
    <div class="ok-sign">
      <img src="https://cdn-icons-png.flaticon.com/512/190/190411.png?w=740&t=st=1686441433~exp=1686442033~hmac=9d8a19fbab79d6e80c848d7a2fe7cf83ee7fc83d7c72bb41ea5061455f71d7f3">
    </div>
    <script>
      setTimeout(function() {
        document.querySelector('.ok-sign').style.display = 'none';
      }, 4000);
    </script>
  <% end %>
</div>


    </div>
    </div>

</body>
</html>

app/views/application/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="https://cdn3.iconfinder.com/data/icons/font-awesome-solid/512/dna-256.png" type="image/x-icon">
    <title>Home | LAB-DFA </title>
    <style>
       @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            border: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
        }

        body {
            background: linear-gradient(45deg, #000000, #ffffff);
            background-repeat: no-repeat;
            min-height: 100vh;
            min-width: 100vw;
            display: flex;
            align-items: center;
            justify-content: center;
        }

            .container {
                background: white;
                width: 800px; /* Reduzido em 30% */
                height: 900px; /* Adicionado uma altura fixa de 500 pixels */
                padding: 1rem;
                box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);
                border-radius: 8px;
            }


        .logo {
            font-weight: 600;
            font-size: 1.5rem;
            margin-bottom: 1rem;
        }

        .menu {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .chart {
            margin-top: 1rem;
            border-radius:  5px;
        }

        .chart-title {
            text-align: center;
            font-weight: 600;
            font-size: 1.2rem;
            padding: 1rem;
            background-color: #f2f2f2;
        }

        .chart-canvas {
            border-radius: 8px;
        }

        .options {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 2rem;
            position: center;
            top: 90%;
            right: 1rem;
            transform: translateY(-50%);
        }

        .options-icon {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin: 0.5rem;
        }

        .options-icon .options-name {
            display: inline-block;
            padding: 0.5rem 1rem;
            background-color: black;
            color: white;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            margin-bottom: 0.5rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">LAB-DFA</div>
        <div class="menu">
            <%= select_tag 'projeto', options_for_select(['Inova', 'ZikaAlliance', 'GAB']), class: 'form-control' %>
            <a href="#"><img src="https://img.icons8.com/material-rounded/24/000000/settings.png"/></a>
        </div>
        <div class="chart">
            <div class="chart-title">Aumento de amostras no biorepositório</div>
            <canvas id="myChart" class="chart-canvas"></canvas>
        </div>
        <div class="options">
            <%= link_to cadastrar_nova_amostra_path, target: "_blank" do %>
                <div class="options-icon">
                    <span class="options-name">Cadastrar nova amostra</span>
                </div>
            <% end %>

            <%= link_to retirar_amostra_path, target: "_blank" do %>
                <div class="options-icon">
                    <span class="options-name">Retirar amostra</span>
                </div>
            <% end %>

            <%= link_to busca_amostra_path, target: "_blank" do %>
                <div class="options-icon">
                    <span class="options-name">Fazer busca de uma amostra</span>
                </div>
            <% end %>
            <%= link_to coleta_path, target: "_blank" do %>
                <div class="options-icon">
                    <span class="options-name">Coleta</span>
                </div>
            <% end %>
            <%= link_to recebimento_path, target: "_blank" do %>
                <div class="options-icon">
                    <span class="options-name">Receber Amostras</span>
                </div>
            <% end %>
        </div>
    </div>

    <!-- Adicionando o script do Chart.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

    <!-- Criando o gráfico com JavaScript -->
    <script>
        // Dados do gráfico
        var xValues = [2017, 2018, 2019, 2020, 2021];
        var yValues = [120, 150, 180, 210, 240];

        // Criando o objeto do gráfico
        var myChart = new Chart("myChart", {
            type: "bar",
            data: {
                labels: xValues,
                datasets: [{
                    backgroundColor: ["grey", "grey", "grey", "orange", "brown"],
                    data: yValues
                }]
            },
            options: {
                legend: { display: false },
                title: {
                    display: true,
                    text: "Número de amostras por ano"
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 300
                        }
                    }]
                }
            }
        });
    </script>
</body>
</html>

app/views/application/recebimento.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Coletora de Amostras</title>
    <style>
	       @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            border: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
        }

        body {
            background: linear-gradient(45deg, #000000, #ffffff);
            background-repeat: no-repeat;
            min-height: 100vh;
            min-width: 100vw;
            display: grid;
            place-items: center;
        }

        .grid-container {
            background: white;
            max-width: 500px;
            padding: 2rem;
            box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            position: relative;
            text-align: center;
        }

        .logo {
            font-weight: 600;
            font-size: 1.5rem;
            margin-bottom: 1rem;
        }

        label {
            display: block;
            margin-bottom: 0.5rem;
        }

        input, select {
            width: 100%;
            padding: 0.5rem;
            border-radius: 4px;
            border: 1px solid #ccc;
            font-size: 1rem;
        }

        button {
            margin-top: 1rem;
            background-color: black;
            color: white;
            padding: 0.5rem 1rem;
            border: none;
            border-radius: 2px;
            font-size: 1.2rem;
            cursor: pointer;
        }

        button:hover {
            background-color: #333333;
        }

        .success-message {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #4CAF50;
            color: white;
            padding: 1rem 2rem;
            border-radius: 4px;
            z-index: 9999;
        }

        table {
            width: 100%;
            margin-top: 1rem;
            border-collapse: collapse;
        }

        th, td {
            padding: 0.5rem;
            border: 1px solid #ccc;
        }

        th {
            background-color: #f2f2f2;
            font-weight: 600;
            text-align: left;
        }

        .centered-heading {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="grid-container">
        <h1 class="logo">Selecione a Coletora</h1>
        <%= form_tag(filtrar_recebimento_path, method: :post, id: 'filtro-form') do %>
         <label for="coletora">Selecione a Coletora:</label>
            <select id="coletora" name="coletora" onchange="document.getElementById('filtro-form').submit()">
                <% @amostras.each do |amostra| %>
                    <option value="<%= amostra.nome_coletora %>"><%= amostra.nome_coletora %></option>
                <% end %>
            </select>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <% end %>

        <h2 class="centered-heading">Amostras Coletadas</h2>
        <table>
            <thead>
                <tr>
                    <th>Nome do Paciente</th>
                    <th>Tipo de Material</th>
                    <th>Data da Coleta</th>
                    <th>Amostra Recebida</th>
                </tr>
            </thead>
            <tbody>
                <% @registros.each do |registro| %>
                    <tr>
                        <td><%= registro.nome_paciente %></td>
                        <td><%= registro.tipo_material %></td>
                        <td><%= registro.data_coleta %></td>
                        <td><input type="checkbox"></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <div id="registros_coletora"></div>
        <button>Receber Amostras</button>
    </div>

        <script>
                function filtrar(coletora) {
                    fetch('/recebimento/filtrar', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    },
                    body: 'coletora=' + encodeURIComponent(coletora)
                    })
                    .then(response => response.text())
                    .then(data => {
                    document.getElementById('registros_coletora').innerHTML = data;
                    });
                }
        </script>

</body>
</html>